-----------------------------------------
-- CREATE A TABLE TO STORE FINGER PRINT DATA-
--------------------------------------------

CREATE TABLE IF NOT EXISTS  CLIENT_FINGER (
   ID INT  AUTO_INCREMENT,
   ID_NUMBER VARCHAR(150) NOT NULL,
   FINGER_INDEX VARCHAR(2) NOT NULL,
   FINGERPRINT BLOB,
   CREATED_BY  VARCHAR(50)  DEFAULT "USER",
   UPDATED_BY  VARCHAR(50)  DEFAULT "USER",
   CREATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
   UPDATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
   PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX PK_ID ON CLIENT_FINGER(ID);
CREATE INDEX INDEX_ID_NUMBER ON CLIENT_FINGER ( ID_NUMBER, UPDATED_TIMESTAMP);

----------------------------------------------
-- CREATE A TABLE TO STORE FINGER PRINT DATA--
----------------------------------------------
INSERT INTO CLIENT_FINGER ( ID_NUMBER,       FINGER_INDEX, FINGERPRINT, CREATED_BY, UPDATED_BY)
                    VALUES( '8205276002177', '02'        ,'WEDSFSFE==',     'USER',     'USER'  );
